export const ADD_STUDENT = 'ADD_STUDENT';
export const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const CANCEL = 'CANCEL';
